"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 3.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'r0%9+)sc89$a%#q$wo)22f*^nute@hb*+gk4s&e^eebwd87m5r'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
	'django.contrib.admin',
	'django.contrib.auth',
	'django.contrib.contenttypes',
	'django.contrib.sessions',
	'django.contrib.messages',
	'django.contrib.staticfiles',
	'django.contrib.sites',
	'app',
	'allauth',
	'allauth.account',
	'crispy_forms',
	'tinymce',
	'ckeditor',
	'django_filters'
]

MIDDLEWARE = [
	'django.middleware.security.SecurityMiddleware',
	'django.contrib.sessions.middleware.SessionMiddleware',
	'django.middleware.common.CommonMiddleware',
	'django.middleware.csrf.CsrfViewMiddleware',
	'django.contrib.auth.middleware.AuthenticationMiddleware',
	'django.contrib.messages.middleware.MessageMiddleware',
	'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
	{
		'BACKEND': 'django.template.backends.django.DjangoTemplates',
		'DIRS': [],
		'APP_DIRS': True,
		'OPTIONS': {
			'context_processors': [
				'django.template.context_processors.debug',
				'django.template.context_processors.request',
				'django.contrib.auth.context_processors.auth',
				'django.contrib.messages.context_processors.messages',
			],
		},
	},
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

# DATABASES = {
# 	'default': {
# 		'ENGINE': 'django.db.backends.sqlite3',
# 		'NAME': BASE_DIR / 'db.sqlite3',
# 	}
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'janet',
        'HOST': '127.0.0.1',
        'PORT': '3306',
        'USER': 'jaymos',
        'PASSWORD': '76661271ID',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
	{
		'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
	},
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'


MEDIA_URL = '/media/'

STATICFILES_DIRS = [
  os.path.join(BASE_DIR, "static")
]

MEDIA_ROOT = os.path.join(BASE_DIR,'media')

SITE_ID = 1
LOGIN_REDIRECT_URL = '/'

CRISPY_TEMPLATE_PACK = 'bootstrap4'
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = ''
EMAIL_HOST_PASSWORD = ''
ACCOUNT_AUTHENTICATION_METHOD = 'username_email'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'

AUTHENTICATION_BACKENDS = [
    # `allauth` specific authentication methods, such as login by e-mail
    'allauth.account.auth_backends.AuthenticationBackend',
]

TINYMCE_DEFAULT_CONFIG = {
	'width':1000,
	'height':400,
	'cleanup_on_startup': True,
	'custom_undo_redo_levels': 20,
	'selector': 'textarea',
	'theme': 'modern',
	'plugins': '''
			textcolor save link image media preview codesample contextmenu
			table code lists fullscreen  insertdatetime  nonbreaking
			contextmenu directionality searchreplace wordcount visualblocks
			visualchars code fullscreen autolink lists  charmap print  hr
			anchor pagebreak
			''',
	'toolbar1': '''
			fullscreen preview bold italic underline | fontselect,
			fontsizeselect  | forecolor backcolor | alignleft alignright |
			aligncenter alignjustify | indent outdent | bullist numlist table |
			| link image media | codesample |
			''',
	'toolbar2': '''
			visualblocks visualchars |
			charmap hr pagebreak nonbreaking anchor |  code |
			''',
	'contextmenu': 'formats | link image',
	'menubar': True,
	'statusbar': True,
}
TINYMCE_JS_URL = '//cdn.tinymce.com/4/tinymce.min.js'

CKEDITOR_CONFIGS = {
     'default' : {
         'toolbar' : [
            [ 'Undo' , 'Redo' ,
              '-' , 'Bold' , 'Italic' , 'Underline' ,
              '-' , 'Link' , 'Unlink' , 'Anchor' ,
              '-' , 'Format' ,
              ' - ' , ' Maximize ' ,
              ' - ' , ' Table ' ,
              ' - ' , ' Image ' ,
              ' - ' ,'Source' ,
              '-' ,'NumberedList' , 'BulletedList'
            ],
            [ 'JustifyLeft' , 'JustifyCenter' , 'JustifyRight' , 'JustifyBlock' ,
              '-' , 'Font' , 'FontSize' , 'TextColor' ,
              '-' , 'Outdent' , 'Indent' ,
              '-' , ' HorizontalRule ' ,
              ' - ' , ' Blockquote '
            ]
        ],
        'height' : 500 ,
         'width' : '100%' ,
         'toolbarCanCollapse' : False ,
         'forcePasteAsPlainText' : True
    }
}


JAZZMIN_SETTINGS= {
     "site_title": "AFROSHOP Admin",
     "site_header": "AFROSHOP",
     "site_brand": "AFROSHOP",
     "welcome_sign": "Welcome to AFROSHOP",
     "show_ui_builder":True,
     "copyright" : "AFROSHOP",
     "changeform_format": "horizontal_tabs",
    "topmenu_links": [
        # Url that gets reversed (Permissions can be added)
        {"name": "AFROSHOP", "url": "home", "permissions": ["auth.view_user"]},
        # model admin to link to (Permissions checked against model)
        {"model": "auth.User"},
    ],
 }

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": False,
    "accent": "accent-primary",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "darkly",
    "dark_mode_theme": "superhero",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}